@startuml BLOGCMS
left to right direction

actor Visiteur
actor Auteur
actor Editeur
actor Admin

rectangle blogCMS {

  (Lire les articles) as UC_Read
  (Créer commentaire) as UC_Comment

  (Authentication) as UC_Auth

  (Créer article) as UC_CreateArticle
  (Gérer article) as UC_ManageArticle
  (Publier article) as UC_PublishArticle

  (Modérer commentaire) as UC_ModerateComment
  (Gérer les articles) as UC_AllArticles
  (Créer catégorie) as UC_Category
  (Gérer utilisateur) as UC_Users
}

Visiteur --> UC_Read

Auteur --> UC_Read
Auteur --> UC_CreateArticle
Auteur --> UC_ManageArticle

Editeur --> UC_AllArticles
Editeur --> UC_PublishArticle
Editeur --> UC_ModerateComment

Admin --> UC_Users
Admin --> UC_Category
Admin --> UC_AllArticles
Admin --> UC_ModerateComment


UC_CreateArticle --> UC_Auth : <<include>>
UC_ManageArticle --> UC_Auth : <<include>>
UC_PublishArticle --> UC_Auth : <<include>>
UC_ModerateComment --> UC_Auth : <<include>>
UC_Users --> UC_Auth : <<include>>
UC_Category --> UC_Auth : <<include>>

@enduml
